version: '2'
services:
  db:
    image: mysql
    volumes:
      - ./mysql_conf:/etc/mysql/conf.d/
    environment:
        MYSQL_ROOT_PASSWORD: "tutorial_db_password"        
        MYSQL_USER: dbb_user
        MYSQL_PASSWORD: tutorial_db_password
        TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./rails_tutorial:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
